Server/app.js

Just a small change to how the server matches map and player names in the DB - this is not super-performant at really high loads tbh, but it should be fine for now.
If it turns out that this is creating problems, we might have to think about adding an extra field in each document for the lowercase version of the names 😕

Make map and player name filter case-insensitive

---

Front/src/app/data-view/data-view.component.ts

Instead of processing samples when creating the points, read in the dataView, so we can iterate over the samples easier

Preprocess samples from dataView

---

Server/app.js

Quick additional route with a query to fetch the available `mapName`s and their occurrences.
Intended to be used for a primary UI to first select the map whose replays you're interested in.

Add map-level aggregate route

---

app/components/viewer/Grid.tsx
app/components/viewer/Viewer3D.tsx
app/lib/api/fileRequests.ts
app/lib/constants/block.ts
app/lib/replays/replayData.ts

Adjust grid by the size of the loaded replays:
* When loading in replays, store their min and max positions
* In the grid, get the min and max position of all replays
* Set center of the grid to the middle of the min and max
* Round center to be at the center of a block position
* Set size to the largest distance along either the X or Z axis (threejs's GridHelper only allows for square grids, so we take the largest distance to cover both the X and Z axis)
* Set grid divisions to the size / 32

Adaptive grid

---

app/components/home/SidebarReplays.tsx

Visible replays were being set from index `currentPage * pageSize` until `(currentPage + 1) * pageSize`, however, when then number of replays is less than `pageSize`, the last elements in the list were undefined. This PR fixes this by limiting the upper limit to the size of the replay array.

Fix setting visible replays

---

app/components/maps/SidebarReplays.tsx
app/lib/utils/time.ts
app/styles/globals.css

- Initialized `visibleReplays` (which means the "Load all visible" button should now always work)
- Removed map column from replay table (since the table is only visible in the context of a single map)
- Made the button column in the replay table wider so the buttons don't move around
- Removed unnecessary (?) scroll styling that led to an inactive scroll bar at all times - we can always change it again, but I think it's just not necessary
- Fixed time strings for values of `1`
- Manually fixed a bunch of icon misalignments due to broken line-heights

Various style fixes and map view cleanup

---

app/pages/maps/[mapUId].tsx

Loads all replays using `Promise.all` instead of awaiting each one separatey

Async load all replays

---

.gitignore
app/components/maps/SidebarReplays.tsx
app/pages/index.tsx
app/styles/globals.css

- Switched to use the default dark theme (to fit the viewer) - no runtime switches possible (yet)
- Removed manual coloring from refresh buttons (to make sure they fit the theme)
- Added VS Code workspace file to .gitignore
The landing page doesn't look amazing cause the background is way too dark - but it works for now, and the whole landing page will change a lot anyway.
We might want to think about letting the user switch between a dark and a light theme at some point - there's some guidance for that in the Ant docs.

Switch to dark theme

---

app/components/maps/MapHeader.tsx

Quick PR to make the header buttons open in a new tab (using Next links and `a` nodes, which also makes middle-click work properly).

Open header links in new tab

---

app/components/maps/MapHeader.tsx

The `exchangeid` in mapInfo can be either `undefined` or `0` (this is what tm.io returns for some maps). This PR disables the TMX button for maps where the TMX id is not valid:

Disable TMX button for invalid TMX IDs

---

app/components/common/HeadTitle.tsx
app/pages/_app.tsx
app/pages/maps/[mapUId].tsx

- Moved analytics and base title into App.
- Kept specific title in HeadTitle - but moved title assembly into the panel so HeadTitle can be reused later.
- Added env var for Google Analytics.

Move generic head into App

---

server/lib/db.js
server/routes/auth.js
server/routes/maps.js
server/routes/replays.js

- Renamed `race_data` collection to `replays`.
- Changed a bunch of stuff in the data model - see the top of each route file for the new ones.
- users
- webid -> webId
- name -> playerName
- login -> playerLogin
- replays
- file_path -> filePath
- Removed map and user fields and replaced them with mapRef and userRef.
- Added logic to handle map and user data for `POST /replays` and the import route (currently duplicate code, but I'm not even sure we want to keep export/import so I didn't spend any effort yet).
- Added query logic for `GET` requests to populate the map and user references when needed.
- While I was working on the API, I added a safety check for replay submissions to reject all requests that were missing required query parameters.
Migration script for local env (and …

Refactor data model (and extract map and user references)

---

server/lib/authorize.js
server/routes/authorize.js
server/routes/logout.js
server/routes/me.js

Changes to the following endpoints:
* `/logout`: if no session is found with the provided `sessionId`, respond with an instantly expiring cookie
* `/me`: if no user is found with the provided `sessionId`, respond with an instantly expiring cookie
This tries to make sure that the client will not have a `sessionId` cookie stored that isn't connected to a valid session/user

Remove invalid sessionId cookies

---

app/components/maps/LoadedReplays.tsx
app/components/maps/SidebarReplays.tsx

When browsing map for the first time, SidebarReplays is opened by default
When loading 1st replay, LoadedReplays is opened by default

set drawers opened by default

---

app/components/maps/LoadedReplays.tsx
app/components/viewer/ReplayLines.tsx

A context was removed from ReplayLines, resulting in the component no longer re rendering whenever a replay color was changed
The line colors useMemo now computes whenever it's replay.color changes

fix replay line colors not updating

---

plugin/Plugin_TMDojo.as

There was a little stutter when plugin uploaded the replay data to the server
That stutter caused a lot of issues, especially on online / dedi servers

Fix replay upload freeze

---

plugin/Plugin_TMDojo.as
server/src/middleware/auth.ts
server/src/routes/replays.ts

- Added server handling for `Authorization` header auth (as opposed to cookie)
- Added logic to refuse replay submissions without auth
- Restructure replay submission request in the plugin to set header
TODO:
- Proper error handling for plugin requests (bit out of scope of this PR though)

Add plugin auth requirement for replay submission

---

app/components/maps/MapHeader.tsx

Disable the trackmania.io button when mapUid is undefined for the current map, preventing you to got to some `tm.io/maps/undefined` link

Disable tm.io button when mapUid is undefined

---

server/src/lib/db.ts

Change order of /maps endpoint aggregate pipeline, basically doing the $group before the $lookup to avoid unnecessary lookups. Was about a 5x speedup or so at this point of the DB, from around 950ms to 200ms.

Improve maps endpoint

---

app/components/mapStats/ReplayTimesHistogram.tsx

Changes histogram tooltip to show natural numbers, plus some additional changes like what the start and end time of each bin is:

Update histogram tooltip

---

app/.eslintrc.js
app/components/mapStats/common/MapStatsTypeSwitcher.tsx
app/components/mapStats/statistics/AggregateMapStats.tsx
app/components/mapStats/statistics/FastestTimeProgression.tsx
app/components/mapStats/statistics/ReplayTimesHistogram.tsx
app/lib/utils/fastestTimeProgression.ts
app/package-lock.json
app/package.json
app/pages/maps/[mapUId]/stats.tsx

Adds personal map statistics to the map stats page. When a user is logged in, the user can toggle between Global and Personal stats using a button at the top. When the user is not logged in, a button is shown that allows the user to log in.

Personal Map Statistics

---

app/components/mapStats/FastestTimeProgression.tsx

Fix format string of tooltip date.
Highcharts axes were not correct on local time. Disabling `useUTC` fixed this.

Fix minutes in tooltip and time axis for time progression chart

---

app/pages/maps/[mapUId]/stats.tsx

Do not set map stats type to personal when the user has no replays. Avoid having the user always click the "Switch to Global statistics" if someone just wants to browse some statistics.

Set map stats type to global if the user has no replays

---

app/components/mapStats/statistics/ReplayTimesHistogram.tsx
app/pages/maps/[mapUId]/stats.tsx

Small update to the website. Previously, when a user was logged in, they would always go to the personal stats if they go to the map statistics page. Now, they only go to that page if they actually have replays on that map.
- #120

[Update] Personal Map Stats - stay on global if user has no replays

---

app/pages/maps/[mapUId]/stats.tsx

Makes sure that the histogram does not have bins of 0.1ms or less when times are really close. Thanks for the find keby :)

Ensure bin size is at least 1 millisecond

---

server/src/lib/db.ts
server/src/routes/auth.ts
server/src/routes/authorize.ts
server/src/routes/replays.ts

As discussed, there's an edge case where new user objects could get the ID `null` since `_id` was not set during creation.
Instead of fixing a duplicate function I removed `saveUser` entirely and replaced it with the already existing `createUser` one - with some additions so we can still get the resulting userID afterwards.

Fix null user ids

---

server/src/lib/db.ts

`upsertedId` will always be `null` because we explicitly perform inserts separately. Instead we can just reuse the existing doc ID we use for the update anyway.

Fix user upsert logic

---

server/src/index.ts
server/src/middleware/auth.ts
server/src/middleware/reqResLogger.ts
server/src/middleware/setupLogger.ts

Extracts some initialization of the logger and request ID and moves this initialization before the auth middleware, so the request ID is available in the auth middleware for logging.

Extract logging middleware + init req id before auth

---

server/src/lib/db.ts
server/src/lib/discordWebhooks/discordWebhook.ts

Adds user count to user alert. In order to keep the flow of the discord webhook non-blocking, I chose to pass the user collection to the webhook method, instead of awaiting the number of users query in the response logic. Also wrapped the whole alert method in a try-catch to ensure that a failing webhook will not cause the endpoint to fail.

Add user count to new user webhook alert

---

server/src/routes/replays.ts

This PR removes player name check, only check WebId.
Replay uploads failed for users that changed their name after logging in the first time.

Only check WebID for replay uploads

---

server/src/lib/authorize.ts

Remove player login validation temporarily, this can result in faulty player logins in the DB, but we don't use player logins anywhere at the moment. Therefore removing validation is not a big problem, we'll just clean the wrong ones up the player login conversion is fixed

Remove player login validation temporarily

---

app/lib/api/apiRequests.ts

Increases default `maxResults` parameter for /replays endpoint calls from `1000` to `10000`. 
In the future, this should be fixed by implementing actual pagination in the replay table, instead of increasing the `maxResults` parameter.

Increase default maxResults for replays endpoint

---

app/components/maps/SidebarReplays.tsx
app/components/viewer/ReplayLines.tsx
app/components/viewer/ReplaySectorHighlights.tsx
app/lib/api/apiRequests.ts
server/src/routes/replays.ts

This PR adds the server changes necessary to store the sector times, recorded by the updated plugin: https://github.com/tm-dojo/plugin/pull/14
Changes:
Backend:
- Accept `sectorTimes` query parameter on the `POST /replays` endpoint
- `sectorTimes` is parsed from a joined string ('1,2,3,4,') to an array ([1,2,3,4]), only accepting integers and non-empty arrays
- These sector times are stored alongside the other replay metadata, inside of the DB document
Frontend:
- Some code for placeholder components, once we get to implementing front-end features for sector time analysis

Server changes for sector times

---

app/components/common/SideDrawerExpandButton.tsx
app/components/maps/SectorTimeTableButton.tsx
app/components/maps/SectorTimeTableModal.tsx
app/components/maps/SidebarReplays.tsx
app/components/viewer/ReplaySectorHighlights.tsx
app/lib/replays/sectorTimes.ts
app/lib/utils/time.ts
app/pages/maps/[mapUId]/index.tsx

- Table displaying date, player name, time, gap to fastest time, and sector deltas to sector times of fastest time
- All deltas are calculated in relation to the fastest, currently selected, replay time
- Color coding for sector times:
- White: default color
- Red: Sector is slower than that sector in the fastest replay
- Green: Sector is slower than that sector in the fastest replay
- Purple: Sector is fastest in that sector of all selected replays
- Theoretical best estimation: 
- Take the fastest sector times from all replays on all sectors, combine these sectors to create a new theoretical best run of these fastest sectors.
- This column displays whether a run has recorded sector times or not. This is not recorded on all runs, as this requires the latest version + a dependency plugin. …

Sector Time Delta Table

---

app/components/maps/SectorTimeTableModal.tsx
app/components/maps/SidebarReplays.tsx
app/lib/replays/sectorTimes.ts
app/pages/maps/[mapUId]/index.tsx

- Improve the sector time replay filter to exclude replays that have fewer sector times recorded than other replays.
- Increase z index sector time table info modal so it's drawn above the sector time table

Sector table fixes

---

app/components/maps/SidebarReplays.tsx
app/pages/maps/[mapUId]/index.tsx

Sector time table is already in staging branch. However, sector times are not reliable yet, so this PR just temporarily removes all the front-end visuals of sector times until they are fixed.

Temporarily remove all Sector Time buttons/visuals

---

app/components/viewer/Viewer3D.tsx

~Draft PR because need to double check edge cases + check possible solution by using the orbit camera ref to set the target, instead of using a state variable (current solution might interfere with replay car camera switches)~
---
Fix issue where camera sometimes gets reset to default position because a variable is used, instead of useState.
Issue happened when a replay was loaded, you skip ahead in the timeline and then change something in the settings.
Fixed by storing the orbit target in a state variable

Fix camera jump issue

---

app/pages/auth_redirect/index.tsx

Add `https://tmdojo.com` to allowed target origins of auth redirect page

Hotfix target origin in auth redirect page for prod domain

---

server/package-lock.json
server/package.json
server/src/index.ts

Use `compression` npm package for response compression. Using the default compression level (6) slowed the request down a bit, so I chose the fastest level (1) as the compression level.
Trying the `/maps` endpoint locally
No compression: 2.2 MB in ~180-190ms
Default compression (level 6): 908 kB in ~220-240ms
Fastest compression (level 1): 956 Kb in ~190-200ms

Add server compression

---

app/components/maps/SidebarSettings.tsx
app/components/viewer/ReplayLines.tsx
app/lib/contexts/SettingsContext.tsx
app/lib/hooks/viewer/replayLines/useUpdateReplayLineTrail.ts
app/lib/replays/replayLineColors.ts
app/lib/singletons/timeLineInfos.ts
app/lib/utils/replay.ts

Still to add/fix:
---
Adds settings to customize replay line trails:
1. Regular line rendering, render complete line
2. Only render replay line from car to the start: reveals line during play
3. Only render a replay line segment of X seconds behind the car: reveals the part directly behind the car while playing, line disappears further than X seconds behind the car
Best demo is checking it out in the preview, loading some replays and adjust the settings in the settings sidebar. Link: https://tm-dojo-git-revealing-replay-line-while-playing-bux42.vercel.app/

Customizable replay line trails

---

app/pages/maps/[mapUId]/index.tsx
app/pages/maps/[mapUId]/stats.tsx

Fix issue for non-uploaded maps where the fetched mapUId was `undefined` and did now work well with navigation between those 2 pages. This PR uses the query mapUId for navigation.

Use query mapUId for navigation between viewer and stats page

---

app/lib/replays/replayLineColors.ts

Change speed color map, to show colors for a larger range.
- `0`: Blue
- `300`: Green
- `600`: Red
- `0`: Red
- `200`: Green

Adjust speed color map (adjusted colors + larger range)
