Bux42/TMDojo

- Front/src/app/data-view/data-view.component.ts
Adds color coding for different gears. Expanded on velocity coloring by adding a gear color map.
> Add gear colors

- README.md
- Server/app.js
- Server/package-lock.json
- Server/package.json
- app/components/home/MapHeader.tsx
- app/components/home/SidebarReplays.tsx
- app/components/home/SidebarSettings.tsx
- app/components/viewer/Viewer3D.tsx
- app/lib/api/fileRequests.ts
- app/lib/api/tmxRequests.ts
- app/pages/index.tsx
- app/styles/globals.css
Added the initial header component but kept it deactivated for now. There's no real point to it now since there's no home page and no map context to link somewhere.
- Formatted README
- Formatted server's `app.js` (sorry, lot of changes - but most are just auto-fixes for style)
- Added API route `get-tmxid` to resolve a `mapUId` to a TMX identifier (used for the link in the UI) - added `axios` dependency to the server as well
- Added `MapHeader` component in the front (see screenshot for basic visuals) - haven't changed any visuals yet, it's just there to have it in place
- Fixed two React errors in the console (array keys and correct `Option` component)
- Changed basic layout to use Ant layout components (makes it much easier to use their header component - maybe also a footer in the …
> Prepare initial header component

- Server/app.js
Merging straight to master for this PR so the server can stay on the master branch.
Adds the vercel preview subdomains to the CORS on the server
> Add vercel subdomain CORS on server

- README.md
Fixes merge conflict between main and staging
> Merge main into staging

- app/components/maps/SidebarReplays.tsx
- app/package-lock.json
- app/package.json
- app/pages/index.tsx
- app/pages/maps/[mapUId].tsx
- app/styles/globals.css
Adds refresh buttons to the index screen and replay sidebar. Mostly just to refresh the replays a bit more easily, probably not a permanent solution/UI.
> Basic refresh buttons

- README.md
- app/.env.local.template
- app/README.md
- plugin/README.md
- server/README.md
- Added README files for each part of the project with some basic information.
- Added analytics ID variable to UI env template (forgot to do that earlier).
I think this is probably fine for now - I'd love to add some real documentation that explains our UI and API structure and some conventions, but we can always do that later.
@MKuijpers @Bux42 Can you guys take a closer look at the plugin README? I'm not sure if those values are still accurate.
> Add basic documentation

- app/components/viewer/TimeLine.tsx
Before, the speed of the timeline was varied by performance and some other random noise. This PR uses a timeout loop which tries to achieve a steady rate by speeding up and slowing down when it notices it did not take as long or as fast as expected (Mainly
Mainly worked off of this answer on stackoverflow: https://stackoverflow.com/a/29972322). Then, assuming the loop is steady, we can update the raceTime accordingly, at a steady rate.
This PR also changes the speed increments, it now has increments of 0.25 from 0.25x to 2.0x.
> Make timeline speed accurate using a steady loop

- app/components/maps/LoadedReplays.tsx
- app/components/viewer/ReplayCars.tsx
- app/components/viewer/TimeLine.tsx
https://imgur.com/ufNxfiw
New feature that changes car size when replay is hovered in LoadedReplays component
> highlight car when replay is hovered in LoadedReplays

- server/lib/authorize.js
- server/routes/authorize.js
- server/routes/logout.js
- server/routes/me.js
Mark Set-Cookie as Secure when `req.secure` is true
> Use Secure cookies

- plugin/Plugin_TMDojo.as
Update TMDojo.as plugin to be compatible with the new OpenPlanet update
> Replace Draw:: with nvg:: for new OP version

- app/components/viewer/ReplayCars.tsx
https://i.imgur.com/8PGb5Ac.gif
Using wheelDamperLen for suspension
> Add wheel suspension

- server/package-lock.json
- server/package.json
- server/src/index.ts
Just a very simple timestamp for the server logs
Format:
> Add timestamp in server logs

- app/components/maps/SidebarReplays.tsx
- app/pages/maps/[mapUId].tsx
When loading replay list in SidebarReplays or refreshing the replay list, a spinner blocks interactions until replays are loaded / refreshed
https://i.imgur.com/mQhWQm6.png
> Loading state in SidebarReplays for loading / refreshing replays list

- plugin/Plugin_TMDojo.as
The recording overlay was still visible when Hud was toggle Off ingame
Not anymore
> hide recording overlay when ingame Hud is Off

- plugin/Plugin_TMDojo.as
A new way to get currentRaceTime has been found for HUD OFF in online mode
This should fix all previous issues regarding HUD OFF recording
> using network ClientScriptAPI to get currentRaceTime && new debug window

- app/components/viewer/ReplayLines.tsx
- app/lib/charts/chartOptions.ts
- app/lib/charts/chartTypes.ts
- app/lib/replays/replayData.ts
- app/lib/replays/replayLineColors.ts
Charts with multiple metrics weren't easy to read
Now both metrics are separated on the same chart
> Splitted charts

- plugin/Plugin_TMDojo.as
Fixed the accidental duplicate commit
> Remove duplicate hudOff initialization

- plugin/Plugin_TMDojo.as
Fixes the duplicate `hudOff` variable initialization in the plugin
> [Hotfix] Plugin fix (duplicate `hudOff` initialization)

- plugin/Plugin_TMDojo.as
This should fix the git repo history on `main`, hopefully
> [Hotfix] Update main with staging history

- plugin/Plugin_TMDojo.as
Final cleanup, investigation has shown rebase doesn't help us - we'll just do normal merge commits and deal with the slight desync.
> Cleanup for last release

- app/components/maps/MapHeader.tsx
> Change TMX button color in map header

- app/components/common/SideDrawerExpandButton.tsx
- app/components/maps/ChartsDrawer.tsx
- app/components/maps/LoadedReplays.tsx
- app/components/maps/SidebarReplays.tsx
- app/components/maps/SidebarSettings.tsx
> Cleanup button designs in map view

- app/components/maps/SidebarReplays.tsx
> smaller button column

- app/components/maps/ChartsDrawer.tsx
- app/components/viewer/TimeLine.tsx
- app/components/viewer/Viewer3D.tsx
- app/components/viewer/timeline/TimeLine.tsx
- app/components/viewer/timeline/TimelineSlider.tsx
Update the timeline UI using a custom timeline slider. Next addition would be to allow time input as it's currently just displaying the time, but for now, this is fine to be merged.
> Timeline UI update

- server/src/lib/db.ts
Previous implementation aggregated all user and map data for the replays pipeline, this PR inserts a $match step on the mapUId as first step, decreasing the amount of user and map data to be aggregated.
`/replays` endpoint went to 1.7-1.8s on average to 40-50ms on average with the current database size
> Filter on map UID as first step in /replays db pipeline

- app/components/mapStats/FastestTimeProgression.tsx
Map stats crashed for the fastest time progression if there were no replays. This PR adds checks for empty replay lists.-
> Fix crash on stats page without replays

- app/components/viewer/timeline/TimeLine.tsx
Title is enough. Just makes sure that the time will stay positive if the next time would be negative
> Ensure time cannot become negative

- app/components/mapStats/statistics/ReplayTimesHistogram.tsx
> Remove console.log in histogram component

- app/components/viewer/Grid.tsx
- app/components/viewer/ReplayCars.tsx
- app/components/viewer/SceneDirectionalLight.tsx
- app/components/viewer/Viewer3D.tsx
Adds a directional light above the scene, pointing down. The light moves whenever replays changes, and moves based upon the center of the replay centers.
Before:
After:
> Lighting + Shadows

- app/components/viewer/ReplayCars.tsx
- app/components/viewer/ReplayChartHoverLocation.tsx
- app/components/viewer/timeline/TimeLine.tsx
- app/lib/singletons/timeLineInfos.ts
- app/lib/utils/math.ts
- app/lib/utils/replay.ts
Interpolation has been implemented at runtime, making everything way smoother
Without interpolation:
With interpolation:
> Runtime interpolation

- app/components/maps/ChartsDrawer.tsx
There was an unfortunate piece of code that was lagging everything the more replays were loaded
> Improve performance on exponential time foreach loop

- app/components/maps/ChartsDrawer.tsx
- server/src/index.ts
- server/src/middleware/auth.ts
- server/src/middleware/reqResLogger.ts
- server/src/middleware/setupLogger.ts
> [Release] Server logging update

- server/src/lib/db.ts
Removes any updates or creation of `last_active`, and adds the `createdAt` value for the user collection
> Add createdAt for user docs

- server/src/lib/authorize.ts
- server/src/routes/auth.ts
Fetch user name from TM API for the /auth endpoint:
- Request access code from TM API
- Request user name from TM API
- Use that fetched user name in user doc
> Use fetched user name from TM API

- server/src/lib/authorize.ts
- server/src/lib/db.ts
- server/src/routes/auth.ts
> [Release] Fetch user names from TM API

- server/src/lib/db.ts
- server/src/lib/discordWebhooks/discordWebhook.ts
- server/src/lib/discordWebhooks/util.ts
Whenever a new user logs in, a message is sent to the internal alerts discord channel.
- Added some utility webhook code to reuse
- Added a `DiscordWebhook` interface which is what will actually be called from the 'business' code
> Add internal webhook for newly joined users

- app/components/landing/ExplanationInfo.tsx
> Change explanation info for "How do I record?"

- server/src/lib/db.ts
Remove client code and object path from some responses
> Remove some fields from queries

- server/src/lib/db.ts
- server/src/routes/replays.ts
> [Release] Only check WebID for replay uploads

- app/components/maps/SidebarReplays.tsx
- app/package-lock.json
- app/package.json
> Replay player name filter improvements

- server/src/lib/authorize.ts
Fix false negative for player login validation
> Add forward slash to playerlogin validation

- server/src/lib/authorize.ts
> [Hot"fix"] Remove player login validation

- app/lib/api/apiRequests.ts
- server/src/lib/authorize.ts
> [Release] Increase maxResults for /replays endpoint

- server/src/middleware/reqResLogger.ts
- server/src/routes/auth.ts
- server/src/routes/replays.ts
Adding the plugin version to replay document
> Add plugin version

- server/src/lib/authorize.ts
- server/src/lib/db.ts
- server/src/routes/authorize.ts
Removes snake_case use case for /user endpoint of the TM API because snake case responses will soon be deprecated in the TM API.
> Remove soon to be deprecated snake_case uses

- app/components/viewer/ReplayCars.tsx
Fixed the follow camera, it no longer looks weird when car moving forward at an angle
Video below with fixed follow camera on left, and old on right
https://user-images.githubusercontent.com/22957968/166142297-14425167-f190-4886-ad99-4b975f480f3c.mp4
> Improve follow camera

- server/package-lock.json
- server/package.json
- server/src/cache.ts
- server/src/lib/db.ts
- server/src/routes/replays.ts
Now using a cache for the maps route, where we had this big mongo query firing every time the /maps route was called
The request was taking ~4 seconds
And now it is ~100 ms
> Implemented basic cache for /maps API

- app/components/viewer/ReplayCars.tsx
- app/lib/replays/replayData.ts
Interpolation had an issue where the first sample of a was modified when changing settings. We now clone the sample to create the interpolated sample.
> Replay sample mutation fix during interpolation

- app/pages/maps/[mapUId]/index.tsx
- server/src/routes/maps.ts
Undo changes in front, check if user is authenticated in backend instead
If user is not authenticated, we send a 401 (Unauthorized), and we don't make the call to tm.io API
> Fix calls to trackmania.io API

- LICENSE
- app/pages/maps/[mapUId]/index.tsx
- server/src/routes/maps.ts
> Check if user is authenticated in backend before calling tm.io
